# Generated by Django 3.0.8 on 2020-08-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200802_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Copies',
            field=models.IntegerField(default=30),
        ),
    ]
